### ISSUE TITLE
Misaligned scroll targeting last item in startIndex/reload

### ISSUE THREAD

**Issue by markushall** [dhilt/ngx-ui-scroll#283] opened 2021-08-17 13:49 UTC
Hi Denis,

Again, thanks for all the work you are putting into this library!

I am experiencing a scroll alignment problem related to `startIndex` setting (or using `reload()`) when targeting _the last item_ in a list.

It occurs when the following is met:
- Setting `minIndex !== undefined`
- Setting `maxIndex !== Infinity`
- Setting `startIndex` same as `maxIndex` OR using `adapter.reload(<maxIndex>)` to scroll the last item into view.
- The last item element _is smaller than_ the second to last item (height-wise)

The use-case here is that I have a nav menu to the left and (virtualized) content to the right on the page. Clicking an item in the menu scrolls the content area to reveal the corresponding section, using `adapter.reload(...)`. Works great for all but the last item, which does not show up properly if it is smaller (in height) than the previous one.

Reproduced in this StackBlitz: https://stackblitz.com/edit/angular-ngx-ui-scroll-to-index-issue?file=src/app/sample-table/sample-table.component.ts

Here we have a list of 100 items (0 - 99). `minIndex` is set to `0`, `maxIndex` to `99` and `startIndex` also to `99`. The only difference is the height of odd/even items. In the far right image, the last item will not show in the viewport. You will have to scroll down to see it.

![image](https://user-images.githubusercontent.com/970037/129733414-34df71b6-1dc4-4b52-ac94-468176c6a6b8.png)

**Comment by dhilt** [comment] 2021-08-18 21:24
@markushall Thanks for good issue and repro, it is a big pleasure to deal with it. What I see:

1. The `minIndex` impact. When `minIndex` is set, the Scroller virtualizes all the dataset on reload. Let's look at "misaligned" sample. The result size of the scrollable container after reload is a sum of rendered [93..99] items and virtual [0..92] items. Rendered items give 50 + 100 + 50 + 100 + 50 + 100 + 50 = 500px. They also give so-called default size value equal to 500 / 7 = 71px, so virtual items give 71 * 93 = 6603px. The final scrollable height is 500 + 6603 = 7103px in this case. When `minIndex` is not set, the virtualization is off. In "Even are larger ok" sample the final scrollable height (after reload) is just a sum of rendered [94..99] items, which is 100 + 50 + 100 + 50 + 100 + 50 = 450px, and default size equal to 450 / 6 = 75px.
2. Where the error appears in "misaligned" scenario. There are two vscroll-workflow inner loops when we do reload(99): one for fetching and rendering the 99th item, which works fine, and another for fetching and rendering [93..98] items, which works wrong. This second workflow loop consists of some steps: pre-fetch calculations, fetch, render and geometry adjustments (including scroll position adjustment). Details are available in [this diagram](https://github.com/dhilt/vscroll/wiki/VScroll-Workflow), the Inner loop section. As we can see from the dev-log, scroll position adjustment goes wrong, the error is 100px. This adjustment depends on different things and also is based on pre-fetch calculations. The problem hides there.

 When the Scroller does its pre-fetch calculations during the second workflow loop, it decides that we need [93..98] items (99th is already rendered). This 6 items is a prediction, which is based on the default size, which is 50px after the first inner loop that was done with only one item (99th) of 50px. So the Scroller thinks that 6 items are needed and it will give 6 * 50 = 300px. But we know, [93..98] will give 100 + 50 + 100 + 50 + 100 + 50 = 450px. Scroller deals with such predictions fine and provides necessary corrections, but this particular case has 1 specific part...

On the 2nd inner loop preFetch there is only one 99th item and in addition to a fetch prediction (6 items) there is also a prediction related to an item that should be the first visible after the render is done. The viewport is 200px, it has the only one item of 50px, and there are 200 - 50 = 150 visible pixels, this 150px space is empty before the 2nd loop render. Currently the position adjustment relies on the top visible point, and the Scroller tries to predict which item should be the top visible in the end. Scroller thinks that the first visible point will be 6*50 - 150 = 150px, so it should be the third (150 / 50)  item from the end of the [93..98] set, which is the 96th item. And this is what we get in the end. The 96th item is the first visible after `reload(99)` in "misaligned" scenario. Not "half of the 98th item and whole the 99th item are hidden", but "96th is the first visible". That's the problem.

This part of pre-fetch predictions should be fixed in the Adjust process logic, it should take into account real sizes and make appropriate correction. This is [the place](https://github.com/dhilt/vscroll/blob/v1.2.0/src/processes/adjust.ts#L74-L81). Sorry for all these verbose thoughts, it helps me keep the situation in mind and brings me closer to a solution.

My plan is to create a test specification for this scenario, then I will think how to fix it. As a temporary workaround I may suggest to perform a scroll down event after the reload is done via `Adapter.fix({ scrollPosition: Infinity })`.

**Comment by markushall** [comment] 2021-08-19 13:47
Thanks for the thorough explanation. Always nice to get a more detailed understanding of what's going on behind the scenes, causing this kind of glitches. And great to hear you have a plan for fixing it. Let me know if I can help out in any way.

Btw, I applied the temporary workaround you suggested and it seems to do the trick for the moment. Customers rejoice!

**Comment by dhilt** [comment] 2021-08-19 16:58
The demo-based test is in git: [issue-283 spec, failing](https://github.com/dhilt/ngx-ui-scroll/commit/b19f90a55f802c5b177d8b53591d1d593a3d3812).

**Comment by dhilt** [comment] 2021-09-01 02:08
@markushall The work is completed, ngx-ui-scroll v2.2.1 is on npm. I decided to introduce a new dev setting to cover this case, and the default value of this setting corresponds to v2.2.0 behaviour. So to have new behaviour fixing the issue you need to change this setting:

```ts
new Datasource({
  get,
  settings,
  devSettings: {
    directionPriority: 'forward'
  }
})
```

Here's the directionPriority description from [the vscroll jsdoc]:(https://github.com/dhilt/vscroll/blob/v1.3.0/src/classes/settings.ts#L102-L113)

> Development setting. Determines the strategy of fixing the difference between estimated and real (rendered) sizes on scroll position adjustments. If set to 'backward', the difference is always resolved in favour of the backward direction: top/left content is fixed and appears in accordance with pre-render expectations. If set to 'forward', both directions could be used, and there is a case when bottom/right content is fixed: new items are to the left of the previously rendered and at least one previously rendered item remains. Default value: 'backward'. Allowed values: 'backward', 'forward'.

This doesn't look very common, and I think the 'forward'-case might be extended in future. Also, it became clear to me that the issue you raised here is not a bug, but might just be a desired behavior for someone else. Direction priority means fixing the position to the top (default) or bottom (rare non-default) line of the estimated rows set. That's why I would not give a strict fix, but an option.

It would be great if you could test it in your environment and provide more cases where it can be used.

**Comment by markushall** [comment] 2021-09-03 12:23
Thanks a lot @dhilt! I have taken a look at the new setting and created another StackBlitz to do some testing. It is sort of a playground where you can alter settings and see what difference they make on the same three lists from the previous SB.

https://stackblitz.com/edit/angular-ngx-ui-scroll-to-index-issue-dir-prio?file=src/app/sample-table/sample-table.component.ts

It seems that with the `forward` setting, my lists now behave the way I expect them to, i.e. start index or reloaded index item always being shown at the top of the viewport. Except, of course, when the item in question is among the last items in the list and the list is not large enough for the item to be at the top. Then I expect the viewport to be scrolled all the way down, to at least bring the item as close to the top as it can be. Hope that made sense.

Will try this outside SB on "real" code next week. Fingers crossed it works equally well there 🙂

**Comment by dhilt** [comment] 2021-09-03 13:55
@markushall Incredible demo you shared! The engineering approach in all its glory. There is another undocumented setting: __[inverse](https://dhilt.github.io/ngx-ui-scroll/#/experimental#inverse-setting)__, it can be useful if you want to have bottom alignment in case of lack of items. Both settings are experimental, but work in the same area. Maybe one day we'll come to their generalization and officialization.

**Comment by markushall** [comment] 2021-09-06 08:09
Nice, we don't have a need for that particular feature right now but I will keep it in mind for whenever the requirement arises!
Since earlier we actually rely a lot on the experimental `viewportElement` and now obviously also the development setting `directionPriority`, so if these features can make it to the official list, no-one would be more happy than me.

**Closed as completed** 2021-09-21 14:15 UTC
