### ISSUE TITLE
How can scroll on one direction?

### ISSUE THREAD

**Issue by rakeshdausa** [dhilt/ngx-ui-scroll#31] opened 2018-03-27 13:42 UTC
After implementing this I got another issue. when I scroll to top data source index is started going negative. I just want it to scroll in positive index. My Data source code is :
```
datasource: Datasource = {
    get: (index, count) => {
      if (index < 0) {
        return Observable.of([]);
      }
      return this.feedsService.getLatestFeeds(this.cursor, false, count).flatMap(value => {
        console.log(index + '    ' + count);
        this.cursor = value.curs;
        console.log(value.matches);
        return Observable.of(value.matches);
      });
    },
    settings: {
      bufferSize: 20
    }
  }
```

**Comment by dhilt** [comment] 2018-03-27 15:45
@rakeshdausa Thanks for the the request! The `feedsService` call should be based on `index` parameter. I don't know what is `this.cursor`, but I would implement the `datasource.get` method as following:

```
datasource: Datasource = {
  get: (index, count, success) => {
    const MIN = 1;
    const start = Math.max(MIN, index);
    count -= start - index; // decrease count if index < MIN
    if (count <= 0) {
      success([]);
    }
    return this.feedsService.getLatestFeeds(start, false, count).flatMap(value => {
      this.cursor = value.curs;
      success(value.matches);
    });
  }, settings: { bufferSize: 20 }
}
```

As you see, I considered the edge cases of scrolling to the topmost position (set by `MIN` value) from random index by calculating `start` value and decreasing `count` value in case of `index` is less than `MIN`.

**Comment by rakeshdausa** [comment] 2018-03-28 06:48
Thank you @dhilt  for your instant response. I have done and its working accordingly but some time when I scroll using scroll bar it showing lot of empty space on the top. And how can I reduce gap between items?

**Comment by dhilt** [comment] 2018-03-28 12:27
@rakeshdausa Since we have done with one scroll direction, I'm going to close this issue. Before you open another one, please look at the demo I created for you – https://stackblitz.com/edit/angular-tfmcme?file=index.html – here I implemented different items heights on the datasource layer (`height: 20 + i`) and bound it via `[style.height.px]="item.height"` on the template. For me it works normally, but if it does not match your case, I would ask you to fork the demo (to reflect your specific infrastructure and reproduce the problem) and open new issue. Thanks!

**Closed as completed by dhilt** 2018-03-28 12:27 UTC

**Comment by rakeshdausa** [comment] 2018-03-28 13:17
Hi, I gone through demo you created. But issue is same in that also. I am sharing video please check it.
https://drive.google.com/open?id=1aMcfqFW3bYOpOq7fkltSZstEsmqvdAy3

**Comment by dhilt** [comment] 2018-03-28 13:46
@rakeshdausa I created new issue and sent you a request to access the google drive.
