### ISSUE TITLE
Extra forward padding 

### ISSUE THREAD

**Issue by StriderRanger** [dhilt/ngx-ui-scroll#111] opened 2019-12-23 16:56 UTC
Sometimes, when there is too few data to fill all the view port, the `height` of the `data-padding-forward` div takes a value bigger than needed, which adds an unnecessary scroll to the list.
This happens randomly, and not much often, that I can't know what is the exact cause or reproduce the problem and share it here.
Any idea of what could possibly cause the height of the `data-padding-forward` div to not be accurate with the remaining empty space of the list?
Thanks!

**Comment by dhilt** [comment] 2019-12-23 20:44
@StriderRanger Is it correct that to reproduce the issue I need to reload the viewport with just few rows datasource and I need do it for some time because it is not guaranteed that the issue will be reproduced on the first try?

**Comment by StriderRanger** [comment] 2019-12-23 21:03
Yes this is the case for me. I tried with [this simple example](https://stackblitz.com/edit/angular-ngx-ui-scroll-initial-height) but even after reloading the result page many times, the extra padding didn't happen.
Please let me know if you need to know any information that may help to investigate further.

**Comment by StriderRanger** [comment] 2019-12-23 21:38
I succeeded on reproducing the problem. In [this example](https://stackblitz.com/edit/angular-ngx-ui-scroll-extra-padding) the extra padding height happens all the time

**Comment by dhilt** [comment] 2019-12-24 02:40
@StriderRanger I investigated your demo and it looks ok for me. The thing is `startIndex` determines first visible item in the viewport. You set `startIndex`  = 1 and it means you'll see "item #&#x2060;1" from above after init/reload. Scroller adjusts paddings to make "item #&#x2060;1" topmost visible. So this behaviour is by design. Does it answer you question or there are some other use cases reproducing the issue?

**Comment by StriderRanger** [comment] 2019-12-24 14:45
Yes I see that the padding is adjusted when the startIndex changes. What happens in my environment is a bit different than that. I'll try to change the example to be more similar to the use case that I have, and I'll keep this post updated.
Thank you very much for your time!

**Comment by StriderRanger** [comment] 2019-12-25 01:06
I have just updated [the example](https://stackblitz.com/edit/angular-ngx-ui-scroll-extra-padding) with a logic similar to what I am using to preload/load the data in the uiScroll, but still the error is not reproduced.
An example that is not reproducing the problem is not very helpful, but I just need to know if you may suspect something susceptible to cause the height of the forward padding to be higher than the remaining empty space in the list?
Thank you again!

**Comment by dhilt** [comment] 2019-12-25 03:05
@StriderRanger There are some points where forward padding could be updated:

1) Append adapter process, [link](https://github.com/dhilt/ngx-ui-scroll/blob/v1.2.2/src/component/processes/append.ts#L50)
2) Clip common workflow process, [link](https://github.com/dhilt/ngx-ui-scroll/blob/v1.2.2/src/component/processes/clip.ts#L32)
3) Adjust common workflow process, [link1](https://github.com/dhilt/ngx-ui-scroll/blob/v1.2.2/src/component/processes/adjust.ts#L75), [link2](https://github.com/dhilt/ngx-ui-scroll/blob/v1.2.2/src/component/processes/adjust.ts#L142), [link3](https://github.com/dhilt/ngx-ui-scroll/blob/v1.2.2/src/component/processes/adjust.ts#L160)
4) Init (common workflow) and reload (adapter) processes, [link](https://github.com/dhilt/ngx-ui-scroll/blob/v1.2.2/src/component/classes/paddings.ts#L47)

I would learn first which process is responsible for the accident. 1 happens only on manual `adapter.append` action. 2 and 3 might happen each time the data is received from datasource. 4 happens only on start and on manual `adapter.reload` action. [Dev mode debug](https://github.com/dhilt/ngx-ui-scroll/tree/v1.2.2#development) might help you to research: 

```
  devSettings: {
    debug: true,
    logProcessRun: true
  }
```

Then we can investigate process params and how your environment can influence them...

I didn't find at first glance anything that might be suspicious in your last demo. Despite I'm not going to blame your data flow logic, I also think that one of the most likely cause of the paddings/scrollPosition inconsistency is datasource indexes inaccuracy. Anyway, the lack of reproduction seems critical.

**Comment by StriderRanger** [comment] 2020-01-01 23:21
Thank you again for your detailed explanation and your constant support :)
When reading the uiScroll logs, I noticed that when the extra padding happens in my environment, it is always due to the miscalculation of the average item size:
- I tested with a list that has 2 items with respectively a height of 79.4px and 87px (including a padding-top of 12px and padding-bottom of 4px)
- The average item size has been logged in the Render process was 20px:

> run Render
> stat before new items render, pos: 0, size: 442, bwd_p: 0, fwd_p: 442, aver: no, items: 0, range: no
> average size has been updated: 20
> stat after new items render, pos: 0, size: 482, bwd_p: 0, fwd_p: 442, aver: 20, items: 2, range: [1..2]

In the same [example](https://stackblitz.com/edit/angular-ngx-ui-scroll-extra-padding) as before, I simulated what I have in my environment by giving a different height to the items along with a padding, but the calculated average item size and the extra padding are both correct.

**Edit:**
After analyzing more closely the code, there is an asynchronous treatment that fills each item's text in the list, and I suspect this treatment to be the cause of miscalculating the average items size in the uiScroll. I updated [my stackblitz](https://stackblitz.com/edit/angular-ngx-ui-scroll-extra-padding) with a reproduction of the problem.

**Comment by dhilt** [comment] 2020-01-02 03:39
@StriderRanger Your last demo revealed the issue at last. This is important case when random row in the viewport might asynchronously change its height after rendering. And for this particular situation Adapter API has `check` method, which (per doc)

> Checks if any of current items changed it's size and runs a procedure to provide internal consistency and new items fetching if needed.

[Here is the updated demo](https://stackblitz.com/edit/angular-ngx-ui-scroll-extra-padding-async-check). I just propagates `onResize` event from `Item` child component and calls `Adapter.check` when it happens. As you can see from the app logs, it re-calculates average row size on demand and adjusts paddings properly. The only think I would like to draw your attention to is that it would be better to run `check` process 1 time for all viewport rows changes instead of doing it multiple times for each row change.

**Comment by StriderRanger** [comment] 2020-01-03 00:33
Thanks for the demo, the problem is "almost" solved: it still happens but far less frequently than usual.

When the problem happens, the average size that is logged in the Check process preserves its previous wrong value, and the Render and Adjust processes are not fired.

From what I noticed, the `check` method performs its job of recalculating the average items size and forward padding correctly, but only when it is called in the right moment.
In the code, the `onResize` event is fired inside the `setTimeout` method, but what would happen if the `setTimeout` doesn't make the browser fire the `onResize` event before rendering the item? I am not sure if this scenario is possible, but if that's the case, probably this is why sometimes the `check` method is run with a wrong average size.

**Comment by dhilt** [comment] 2020-01-03 03:25
@StriderRanger You are right, the time of the `Adapter.check` method call should be chosen properly, DOM element must get its final dimensions before the call. That's why I used `setTimeout` in the demo, to let the browser to apply size changes. The real life use cases should be considered carefully/individually, but anyway it is a developer responsibility to guarantee right sequence of events: initial row render --> row size change --> resize handler call.

If you don't know the time of change but you are sure that it will happen, you might implement your own DOM element size listener and call `Adapter.check` when this listener is being triggered. Simplest implementation could be no more than `setInterval` polling of `element.clientHeight` value. From the other hand you may follow more complex approach, like [this library](https://github.com/juggle/resize-observer).

**Comment by StriderRanger** [comment] 2020-01-10 17:43
@dhilt Thanks for your proposition. I implemented the [resize-observer](https://github.com/juggle/resize-observer) lib, and it is working but with a slight additional forward-padding size (1px to 2px of difference). You can test the behavior in [this sample](https://stackblitz.com/edit/angular-ngx-ui-scroll-extra-padding-async-check-resizeobserver).

Upon running the `check` process this is what has been logged:
`stat check, pos: 0, size: 250.39999389648438, bwd_p: 0, fwd_p: 76, aver: 44, items: 4, range: [1..4]`
If we assume that the formula of calculating the forward-padding is `fwp_p = size - aver * items` then the `fwd_p` should be equal to: 74.39, whereas the logged value is 76

If this additional info could help to understand better the sample
, I followed your advice so to call the `Adapter.check()` method as few times as possible by implementing this logic:
1. In the _view-list_ component (app.component.ts):
I created an array that holds the ids of the items that are pushed to the data, and once an item has resized and the event is propagated, its id is removed from the array. The idea here is call the `Adapter.check()` method once the array is empty (i.e: all the items have been size-checked)
The `Adapter.check()` is run after the adapter finishes all pending processes: I had to apply this change because I run into the `Cannot read property 'tagName' of undefined` error in my environment where the list has many items.
2. In the _item_ component (item.component.ts):
The resize event is not emitted till the item has some content, and its height is higher than a prefixed min-height.

**Comment by dhilt** [comment] 2020-01-10 19:16
@StriderRanger Thanks! I'll take a look for the demo you just posted, but first I'd like to put some thoughts

 - I don't like fractional size of the viewport and padding DOM elements (though fractional average item size is fine), this is something about different browsers support, for example see [this chromium bug](https://stackoverflow.com/questions/52470549/subpixel-scroll-issue-cant-set-scrolltop-properly-on-chrome-69) I discovered in 2018
 -  `'tagName' of undefined` should be fixed on the ui-scroll end for you will not need to wait for the ui-scroll stops, there is issue https://github.com/dhilt/ngx-ui-scroll/issues/112 related to this problem; also you may try to replace `isLoading` workaround with `loopPending` (may work faster)
- great to hear `resize-observer` works, this demo might be helpful for others

**Comment by dhilt** [comment] 2020-01-15 07:00
@StriderRanger Let's discuss this screenshot for we may get how this works:

<img width="736" alt="Screenshot 2020-01-15 at 09 18 53" src="https://user-images.githubusercontent.com/4365660/72409910-1e2b9f80-3778-11ea-8bce-415659e7b39e.png">

Average item size in this particular case is not involved in padding size calculation because we have only 4 items which exist in the viewport, so the DOM dimensions are taken into the account. And the DOM dimensions are fractional. 

34.16 + 52.34 + 34.16 + 52.34 = 173 // real items size
250 - 173 = 77 // padding size based on DOM dimensions

Average item size is needed for dealing with virtualized rows. In this point (4 items, minIndex = 1 and maxIndex not defined) we have no virtual rows. 

250 - 44 * 4 = 74 // padding size based on average sizes, wrong

That's the main difference. Also, we can see that the real padding size is different from what we just supposed it to be

<img width="832" alt="Screenshot 2020-01-15 at 09 28 01" src="https://user-images.githubusercontent.com/4365660/72410480-74e5a900-3779-11ea-977d-ef58fc5ff169.png">

The diff is about 0.01. And I can't overcome fractional values logged as "size", "bwd_p" and "fwd_p" because they are taken from DOM. This shifts us closer to the cause of the confusion.

You may also ask, why do we have `fwd_p: 76, aver: 44` and `fwd_p: 77, aver: 43` at the same point? And I think I know the answer, this is browser/OS scaling I mentioned [there](https://stackoverflow.com/questions/52470549/subpixel-scroll-issue-cant-set-scrolltop-properly-on-chrome-69). My values can be reproduced with 110% scaling, your ones with 125% (in my environment). Setting scale to 100% I don't see any issues.

**Comment by StriderRanger** [comment] 2020-01-15 13:53
@dhilt Thanks! That clarifies the reason of this behavior, which is related to the scaling of the browser that is used for testing. It also corrects the padding formula that I speculated, as I didn't know that the average size is used only for virtualized rows.

So to sum up the cause of the extra padding space was the asynchronous process of filling the items, and to amend it the [resize-observer](https://github.com/juggle/resize-observer) lib was used to detect when the items resize, and then the `Adapter.check` method was called so that the ui-scroll list becomes more consistent with the new/real size of the items. [This sample](https://stackblitz.com/edit/angular-ngx-ui-scroll-extra-padding-async-check-resizeobserver) was a way of implementing this logic.

**Comment by dhilt** [comment] 2020-01-15 14:47
A good job we've done, I guess.
Thanks!

**Closed as completed by dhilt** 2020-01-15 14:47 UTC

**Comment by brabenetz** [comment] 2020-09-23 10:12
I'm not sure if it's the right solution (looks a little like a hack).

Even if the last entry of my entries was in the visible area, the data-padding-forward  had a synthetic height which triggered the display of an unnecessary scrollbar.

**My Solution**:
- I subscribe lastVisible$ and check if this is the last value from myItems ("eof$" was not triggered reliable for that usecase. Maybe eof$ is only triggerd if the last item is fully visible which was not enough for my usecase)
- Then I manually set  style="height: 0px;" on data-padding-forward (see correctDataPaddingForwardElementHeight(...))

**My Feeling**:
This seems to work fine, but my feelings expects a better solution?
Like an optional settings property "hideDataPaddingForwardIfLastItemVisible=true", or something similar?

**The anonymized code:**
```TypeScript
myItems: DummyItem[] = [];
myItemsDataSource: IDatasource = new Datasource({
	get: (index, count, success) => {
		const data = [];
		for (let i = index; i <= index + count - 1; i++) {
			const d = this.myItems[i];
			if (d) {
				data.push(d);
			}
		}
		success(data);
	},
	settings: {
		startIndex: 0,
		minIndex: 0,
		bufferSize: 1,
		padding: 0,
	},
	// devSettings: {
	//     debug: true,
	//     immediateLog: true,
	// }
});
subscriptions = new Subscription();

ngOnInit(): void {
	this.subscriptions.add(this.myItemsDataSource.adapter.lastVisible$.subscribe((lastVisible) => {
		// Last Item of myItems is Visible => data-padding-forward should be zero.
		if (lastVisible.$index === this.myItems.length - 1) {
			this.correctDataPaddingForwardElementHeight(lastVisible.element.parentElement);
		}
	}));
	....
}

set myItems(myItems: DummyItem[]) {
	this.myItems = myItems;
	this.myItemsDataSource.settings.maxIndex = this.myItems.length - 1;
	this.myItemsDataSource.adapter.reset();
}

ngOnDestroy(): void {
	this.subscriptions.unsubscribe();
}

/** Correct height to Zero: <div data-padding-forward style="height: 0px;"></div> */
private correctDataPaddingForwardElementHeight(viewportElement: HTMLElement): void {
	const dataPaddingForwardElement: HTMLElement = viewportElement.querySelector(`[data-padding-forward]`);
	if (dataPaddingForwardElement) {
		// console.log('set dataPaddingForwardElement height', dataPaddingForwardElement);
		dataPaddingForwardElement.setAttribute('style', 'height: 0px;');
	}
}
```
