### ISSUE TITLE
Error while trying to invoke reload() method

### ISSUE THREAD

**Issue by boskras** [dhilt/ngx-ui-scroll#112] opened 2020-01-03 14:19 UTC
Hi,
I'm using uiScroll with ngrx. Via NGRX I'm sending the new position that I would like to render the list with reload() method. But I'm getting this strange error - I've tried to find some workaround but unfortunately, I failed. 
Maybe some of you can help me?

```
core.js:15724 ERROR TypeError: Cannot read property 'tagName' of undefined
    at Routines.push../node_modules/ngx-ui-scroll/fesm5/ngx-ui-scroll.js.Routines.getParams (ngx-ui-scroll.js:1207)
    at Routines.push../node_modules/ngx-ui-scroll/fesm5/ngx-ui-scroll.js.Routines.getEdge (ngx-ui-scroll.js:1289)
    at Viewport.push../node_modules/ngx-ui-scroll/fesm5/ngx-ui-scroll.js.Viewport.getElementEdge (ngx-ui-scroll.js:1616)
    at ngx-ui-scroll.js:4950
    at Array.find (<anonymous>)
    at Function.push../node_modules/ngx-ui-scroll/fesm5/ngx-ui-scroll.js.End.calculateParams (ngx-ui-scroll.js:4949)
    at Function.push../node_modules/ngx-ui-scroll/fesm5/ngx-ui-scroll.js.End.run (ngx-ui-scroll.js:4889)
    at ngx-ui-scroll.js:5148
    at Workflow.push../node_modules/ngx-ui-scroll/fesm5/ngx-ui-scroll.js.Workflow.process (ngx-ui-scroll.js:5294)
    at SafeSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub (Subscriber.js:196)
```

My invoke:
`this.datasource.adapter.reload(vsSettings.reloadIndex);`

**Comment by dhilt** [comment] 2020-01-05 18:33
Thanks @boskras! This is very interesting issue and right now I have no idea how it could happen. `'tagName' of undefined` means some DOM element was not found after render. To prove it, may I ask you to look at dev log (`settings.debug` must be true, see [doc](https://github.com/dhilt/ngx-ui-scroll/tree/v1.2.2#development))? You should get following error in the console:

> Can\'t associate item with element

Then, we'll need to debug it and the best option to do it would be to have a standalone repro. If it is possible, you may fork [this stackblitz](https://stackblitz.com/edit/angular-ngx-ui-scroll-1-2-2-auto-prepend-when-bof) and ship there your app logic related to the issue.

**Comment by boskras** [comment] 2020-01-07 07:52
I think that I've tracked this problem.
In my implementation I'm using `ngx-ui-scroll` with more complex components, sometimes they have a lot of data to analyze or render inside them, that's why they sometimes take a little bit more time to render/init than expected.

When this complex component with a large amount of data takes too much time during rendering, 'the lib' try to scroll into this component but it can't because this component is still initializing. This is my guess but it seems to be very like to be true. I'll try to simplify my components to decrease init time and will look if it will solve this issue.

**Comment by boskras** [comment] 2020-01-07 11:30
Ok, I found the solution. My previous guesses were false. It turned out that `reload()` function had to be wrapped with `setTimeout()`
```
this.store.select(fromRoot.getUiVsSettings)
    .subscribe(vsSettings => {
      if (vsSettings.startIndex === vsSettings.reloadIndex && vsSettings.reloadIndex !== this.vsReloadIndex) {
        this.vsReloadIndex = vsSettings.reloadIndex;
        setTimeout(() => {
          this.datasource.adapter.reload(this.vsReloadIndex);
        });
      }
    })
```

**Comment by dhilt** [comment] 2020-01-08 05:59
@boskras Despite I'm glad to know you have found a workaround, I really don't like `setTimeout` there... Could you please turn debug logging on and run both variants (broken and fixed, with and without `setTimeout`) sequentially, save console logs and send them to me? (attaching the log files to the reply would work) There are two areas of where the problem might be: the app architecture specificity and the lib bug. I'm afraid of the second one. Dev log should shed some light.

**Comment by boskras** [comment] 2020-01-09 12:16
Ok so here are the logs.

[cannot-read-property_tagName_with-setTimeout_1578571905423.log](https://github.com/dhilt/ngx-ui-scroll/files/4040297/cannot-read-property_tagName_with-setTimeout_1578571905423.log)
[cannot-read-property_tagName_1578571905423.log](https://github.com/dhilt/ngx-ui-scroll/files/4040298/cannot-read-property_tagName_1578571905423.log)

**Comment by dhilt** [comment] 2020-01-09 20:04
@boskras  Yep, it's definitely the lib issue. Async reload should properly intercept the ui-scroll workflow if any processes are running (like render), and looks like we didn't cover all cases. In you case (without timer) the reload is being fired right after the render process had been started. And this is what the log reveals: reload process resets the viewport and cleans up the data state, and then the render process of the previous cycle takes the control and tries to do its work as if the viewport had not been cleaned. That is wrong behaviour, it should be fixed on the ui-scroll end. Timer's just allowing you to pass through the previous cycle render without the need of interception.

With your log I think I'll be able to reproduce the problem in tests, then I'll fix it. So let this issue remain open.

**Comment by dhilt** [comment] 2020-01-09 20:13
@boskras The better workaround would be to replace `setTimeout` with `loopPending` subscription. What is `loopPending` you may read [here](https://dhilt.github.io/ngx-ui-scroll/#/adapter#is-loading-advanced). But in two words it would allow you to wait until current fetch-render procedure is resolved:

```
  const sub = this.datasource.adapter.loopPending$.subscribe(pending => {
    if (!pending) {
      sub.unsubscribe();
      this.datasource.adapter.reload();
    }
  });
```

**Comment by StriderRanger** [comment] 2020-01-19 01:02
@dhilt I have another case that reproduces the same `Cannot read property 'tagName' of undefined` error.
In [this sample](https://stackblitz.com/edit/angular-ngx-ui-scroll-append-tagname-err), I want to append a new item to the dataset, and the error occurs while calling the `Adapter.append()` method. I tried to use the `loopPending$` observer but the append didn't work at all.

**Edit:** I think that in my sample, the Adapter.check() method that is run after listening to the resize event, is responsible for this error

**Comment by dhilt** [comment] 2020-01-19 04:47
@StriderRanger Having the repro on stackblitz I was able to catch the issue in 15 minutes, that's really helpful! Of course, we see `'tagName' of undefined` error, but the main problem arises from these 3 lines of dev log (the last Workflow cycle, related to Adapter.append call):

> stat before new items render ... items: 4, range: [1..4]
> **item 5 has resized (1) times, with height 18**
> stat after new items render ... items: 4, range: [1..4]

You see, nothing's changed after render, the scroller didn't get new item. And the previous Adapter.check call is responsible for this, not the resize procedure you implemented in the Item component (it just highlights the issue). I think I'm almost ready to fix it, but anyway let's devote a separate issue to it: [Adapter.check() does not clean up the state properly](https://github.com/dhilt/ngx-ui-scroll/issues/123).

________

Btw the `Adapter.reload()` issue is almost done,  the [PR](https://github.com/dhilt/ngx-ui-scroll/pull/117) is ready to merge, I just want to double-check things.

**Comment by dhilt** [comment] 2020-01-24 14:39
The case is done. No special actions are needed to avoid wrong behaviour since v1.3.0, the lib handles it internally. Please check v1.3.0 and open a new issue if any questions or concerns.

@boskras ^^

**Closed as completed by dhilt** 2020-01-24 14:39 UTC
Labels: bug
